Add automatic key retrieval on signature verification
Signed-off-by: Mike Detwiler <mike.detwiler@gmail.com>

diff --git a/scripts/get-gnu-tool b/scripts/get-gnu-tool
--- a/scripts/get-gnu-tool
+++ b/scripts/get-gnu-tool
@@ -21,6 +21,19 @@ function usage()
 	eof
 } # usage()
 
+function cleanup()
+{
+  local dir=$1
+
+  if [[ -d $dir ]]; then
+    if rm -rf $dir; then
+      echo "Removed $dir"
+    else
+      echo "Failed to clean $dir"
+    fi
+  fi
+}
+
 prefix=""
 exec_prefix=""
 flags=""
@@ -59,25 +72,48 @@ tmpdir=$(mktemp -d)
 
 if ! pushd $tmpdir; then
   echo "Failed to create temporary directory"
+  cleanup $tmpdir
   exit 1
 fi
 
 toolname="$tool-$version"
 archive="$toolname.tar.gz"
+signature="$archive.sig"
 url="$baseurl/$tool/$archive"
+signurl="$baseurl/$tool/$signature"
 
 if ! wget $url; then
-  echo "Failed to donwload $url"
+  echo "Failed to download $url"
+  popd
+  cleanup $tmpdir
+  exit 1
+fi
+
+if ! wget $signurl; then
+  echo "Failed to download $signurl"
+  popd
+  cleanup $tmpdir
+  exit 1
+fi
+
+if ! gpg --keyserver-options auto-key-retrieve --verify $signature; then
+  echo "Failed to verfiy signature $signature"
+  popd
+  cleanup $tmpdir
   exit 1
 fi
 
 if ! tar -xzf $archive; then
   echo "Failed to extract $archive"
+  popd
+  cleanup $tmpdir
   exit 1
 fi
 
 if ! pushd $toolname; then
   echo "Failed to change directory to $toolname"
+  popd
+  cleanup $tmpdir
   exit 1
 fi
 
@@ -87,31 +123,28 @@ echo
 
 if ! ./configure $prefix $exec_prefix $flags; then
   echo "Failed to configure $toolname"
+  popd
+  cleanup $tmpdir
   exit 1
 fi
 
 if ! make $makejobs; then
   echo "Failed to make $toolname"
+  popd
+  cleanup $tmpdir
   exit 1
 fi
 
 if ! make $makejobs install; then
   echo "Failed to install $toolname"
+  popd
+  cleanup $tmpdir
   exit 1
 fi
 
 popd
-
-if ! rm -rf $toolname $archive; then
-  echo "Failed to clean $toolname"
-  exit 1
-fi
 
 echo "Successfully installed $toolname"
 
 popd
-
-if ! rm -rf $tmpdir; then
-  echo "Failed to clean $tmpdir"
-  exit 1
-fi
+cleanup $tmpdir
